### ISSUE TITLE
Unable to operate

### ISSUE THREAD

**Issue by HaoZhaiZi** [PSYZ1234/NIDALoc#3]
We executed this procedure using the NCLT Dataset, but encountered the following issues. How should it be amended？
Traceback (most recent call last):
  File "E:\work\Brainslam\NIDALoc\train.py", line 442, in <module>
    train()
  File "E:\work\Brainslam\NIDALoc\train.py", line 218, in train
    train_one_epoch(model, train_loader, scheduler, epoch, train_writer, loss, device)
  File "E:\work\Brainslam\NIDALoc\train.py", line 223, in train_one_epoch
    for _, (train_data, train_pose, train_grid, train_hd) in enumerate(train_loader):
  File "D:\anaconda\envs\NIDA\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\anaconda\envs\NIDA\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\anaconda\envs\NIDA\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda\envs\NIDA\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\work\Brainslam\NIDALoc\data\composition.py", line 58, in __getitem__
    clip  = [self.dset[i] for i in idx]
  File "E:\work\Brainslam\NIDALoc\data\composition.py", line 58, in <listcomp>
    clip  = [self.dset[i] for i in idx]
  File "E:\work\Brainslam\NIDALoc\data\NCLT_datagenerator.py", line 177, in __getitem__
    scan      = np.fromfile(scan_path, dtype=np.float32).reshape(-1, 4)  # (N, 4)
ValueError: cannot reshape array of size 38614 into shape (4)

**Comment by liw95** [comment]
You can refer to DiffLoc (https://github.com/liw95/DiffLoc), where we propose the processing code [nclt_precess.py](https://github.com/liw95/DiffLoc/blob/main/preprocess/nclt_precess.py).

**Comment by HaoZhaiZi** [comment]
Thank you very much. In addition, may I ask whether the BioSLAM algorithm has also been implemented? I have asked the author of BioSLAM (A Biologically-Inspired Simultaneous Localization and Mapping System Based on LiDAR Sensor, IROS 2022). But they failed to give a clear answer.

**Comment by HaoZhaiZi** [comment]
> You can refer to DiffLoc (https://github.com/liw95/DiffLoc), where we propose the processing code [nclt_precess.py](https://github.com/liw95/DiffLoc/blob/main/preprocess/nclt_precess.py).
Thank you very much. In addition, may I ask whether the BioSLAM algorithm has also been implemented? I have asked the author of BioSLAM (A Biologically-Inspired Simultaneous Localization and Mapping System Based on LiDAR Sensor, IROS 2022). But they failed to give a clear answer.
